export const UPDATE_IMAGE = 'UPDATE_IMAGE';

export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const LOCATION_CHANGED = 'LOCATION_CHANGED';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';

export const TEMPERATURE_UNITS_CHANGED = 'TEMPERATURE_UNITS_CHANGED';
export const CHANGE_TEMPERATURE_UNITS = 'CHANGE_TEMPERATURE_UNITS';

export const APPLICATION_READY = 'APPLICATION_READY';
export const API_REQUEST = 'API_REQUEST';
